### ISSUE TITLE
Move from heroku to larger DigitalOcean droplet with dokku

### ISSUE THREAD

**Issue by merwok** [jeremymoreau/covid19mtl#12]

**Comment by merwok** [comment]
@jeremymoreau  I have done basic sysadmin for Debian VMs on DO and am curious about Dokku as Heroku replacement, so ping me if I can help here!

**Comment by jeremymoreau** [comment]
@merwok Thanks! yes, also my first time using dokku, so just reading the docs and playing around with it before I point the real domain to it (and potentially break things...). It was pretty easy to setup with the [1-click dokku DO installation](https://marketplace.digitalocean.com/apps/dokku)
