### ISSUE TITLE
Buttons and/or seperate log and log-log plots?

### ISSUE THREAD

**Issue by gdevenyi** [jeremymoreau/covid19mtl#2]
The log space is obviously more helpful for visualization

**Comment by gdevenyi** [comment]
And here I was thinking you were ignoring my issues : https://twitter.com/sylvain_baillet/status/1247584874892058624

Congrats!

**Comment by jeremymoreau** [comment]
Thanks!! Indeed, a busy time right now :) This feature was more work than the last issue so didn't add it right away. It's up now with changes in 316dff9d289a52974fa9822eac077b0e4ac0d51a
