### ISSUE TITLE
Share on the show-and-tell forum?

### ISSUE THREAD

**Issue by chriddyp** [jeremymoreau/covid19mtl#3]
Hey @jeremymoreau  - This app looks great! Would you mind sharing this on the show-and-tell category of the Dash forum? https://community.plotly.com/tag/show-and-tell. There's been quite a few covid-19 apps published & shared by the community and I'm sure they'd appreciate seeing another one.

**Comment by jeremymoreau** [comment]
Thanks @chriddyp ! I've just posted it. This was my first time building an app with Dash and Plotly and it was really nice to work with! Thanks a lot for making this software!! :)
