### ISSUE TITLE
Move dash initialization out of __init__

### ISSUE THREAD

**Issue by mschoettle** [jeremymoreau/covid19mtl#31]
The dash/app initialization is currently in `__init__.py` which slows down `refreshdata` significantly. Can this be moved somewhere else? Maybe into `__main__.py`?

**Comment by jeremymoreau** [comment]
Turns out this breaks the deploy since the production gunicorn server on Dokku expects the Dash app to be initialised (and `server = app.server`) to be in `__init__.py`. Maybe an easier solution would be to move `refreshdata` outside of `/app`? This script is entirely independent from the core Dash app so this probably makes sense in any case.

**Comment by merwok** [comment]
Have you tried with `gunicorn app.__main__:app`?

Alternatively, moving refreshdata makes sense!

**Comment by mschoettle** [comment]
One problem with `refreshdata` being in the root is that it cannot be imported by another script anymore since it is not in a module.

**Comment by merwok** [comment]
Is that a problem?  In general, a Python file should be a module or a script.  But if another script needs functions from refreshdata, if they are in the same directory then imports would work.  What is the need?

**Comment by jeremymoreau** [comment]
If there is a need in the future, we could put it under `/refreshdata/refreshdata.py`. I don't think there is any reason currently for a script in `/app` to call functions in `refreshdata.py` (since everything in `/app` involves the frontend Dash app).

**Comment by mschoettle** [comment]
It's only a temporary problem :) I am currently importing `refreshdata` in another script that calls the functions of `refreshdata` to add past data. If you they are both in the project root you get `ImportError: attempted relative import with no known parent package`.

I worked around it locally by copying refreshdata to a `scripts` directory/module since this is only temporary until the past data is included.

**Comment by merwok** [comment]
Ah! You can’t do `from .refreshdata import func` from your other script because they are not part of a package, but you could do `from refreshdata import func`.

**Comment by mschoettle** [comment]
Ah, indeed, thanks! Didn't know about that.
