### ISSUE TITLE
Determine actual date of data

### ISSUE THREAD

**Issue by mschoettle** [jeremymoreau/covid19mtl#34]
When retrieving the data from Santé Montreal, it is assumed that the state of the data is from yesterday. However, it occasionally happens that the data is not updated. This happened last this week on Nov 25th. Also on the weekend the data is not updated (on Monday the data from Sunday is shown so Fri and Sat are usually missing).

To automate scraping and processing, we need to make sure that this is detected.

I see two ways:

* don't append data if the exact same data exists for the previous day(s)
* extract the date from the HTML page (the minibox on top of the page is often updated earlier than the data in the tables)

**Comment by ygingras** [comment]
I can write the selector for extracting the date if you give me the url of the page where it can be found.

**Comment by mschoettle** [comment]
Thanks!

For Santé Montreal: https://santemontreal.qc.ca/en/public/coronavirus-covid-19/situation-of-the-coronavirus-covid-19-in-montreal/

Under the first table is a line:

> Source : Fichier Trajectoire de santé publique (TSP), extracted on 26 November, 5:31 PM

There is also one further at the top ("Data as of November 27, 2020, at 12 p.m.") but I think that applies only to the numbers just below.

For INSPQ: The actual date is not on the page directly (https://www.inspq.qc.ca/covid-19/donnees) but shows up after. My guess is that it is taken from https://www.inspq.qc.ca/sites/default/files/covid/donnees/manual-data.csv and then inserted using JS.

**Comment by ygingras** [comment]
For INSPQ, indeed, there is some magic JS going on to update the date element.  It happens shortly after the page loads both 
 https://www.inspq.qc.ca/sites/default/files/covid/donnees/manual-data.csv
and 
  https://www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv
(passing randNum=26782617 as a get param, but I don't think you actually need it).  As of right now, the date shown on the page is the last data cell in the CSVs (yesterday), NOT the Last-Modified HTTP header (today), so fetching the CSV directly is the right way to go.

Santé Montréal seems to be down right now.  I will write the selector once they come back up.

**Comment by mschoettle** [comment]
Thanks for looking into this. I think `manual_data.csv` is used for the info boxes at the top. On Nov 26th (so expecting to see data from the 25th) they had this note on top of their page: "En date du 26 novembre, seules les données des tuiles de la page principale ont été mises à jour. Le reste des données sera mis à jour dès que possible."

In manual, there was the 25th, in covid19-hist, there the last date was the 24th.

For Santé Montréal it is similar I think (except no machine-readable data). They have their info boxes on top which seem to be updated at noon, whereas the detailed data is updated later in the day.

**Comment by ygingras** [comment]
Santé Montréal is still not working for me.  I keep getting timeouts, even after trying from a few different IPs.  Maybe they block non-Canadian IPs?  If it's still up for you, please attach the HTML and I will give you selector.

**Comment by mschoettle** [comment]
Yes, they seem to be doing that for some reason. I notified them this week, not sure if it will be fixed though.

You can find the scraped HTML page here:
https://github.com/jeremymoreau/covid19mtl/blob/add-data/app/data/sources/2020-11-25/data_mtl.html

**Comment by ygingras** [comment]
The data on that page is not very well tagged, but we already new that.  Assuming that the date stays in bold and that your refresher is only concerned about the first stated date, you can do like this:

```
date_elems = [el for el in soup.select('div.csc-textpic-text p.bodytext b') 
            if el.text.startswith('Data as of')]
el = date_elems[0]
label = el.text.replace('Data as of', '')
label = label[:label.index(', at')]
refresh_date = dateutil.parser.parse(label)

```

You will need to add `dateutil` to requirements.in.  I have not kept up to speed with all the changes to refreshdata.py, so I will let you put the date extraction in there since you probably know better then me where it should go.

**Comment by mschoettle** [comment]
Thanks @ygingras! I managed to adjust it slightly to get the date from the text under the table (`extracted on ...`).

**Comment by mschoettle** [comment]
I think the refresh part needs to be split into MTL and QC specific parts to fully support just downloading and updating either data. Alternatively, the data could be downloaded regardless and only the updating part be adjusted if the data date is the expected one.
