### ISSUE TITLE
Schedule refreshdata.py to run daily and deploy changes automatically

### ISSUE THREAD

**Issue by jeremymoreau** [jeremymoreau/covid19mtl#37]
Once the missing data are added and `refreshdata.py` is able to update all the data sources without any manual intervention, it'd be nice to have it run automatically daily without any user input.

Since the Dokku server has no persistent storage (it is overwritten on every new deploy), I was thinking we could maybe use github actions to do this (e.g. using https://jasonet.co/posts/scheduled-actions/). We'd setup a `schedule` event to run `refreshdata.py` daily and commit the updated data files back to the repo.

I've set up a workflow that will automatically deploy the `deploy` branch to the Dokku server (https://github.com/jeremymoreau/covid19mtl/blob/master/.github/workflows/main.yml)

**Comment by mschoettle** [comment]
Totally agree.

Cool, didn't know such things were possible with GitHub actions. I was going to offer to run this with a cronjob on my server or Raspberry Pi. But something independent could be better to avoid relying on someone specific.

I am currently running this on my Raspberry Pi every day at 23:00. Currently, requests from certain networks seem to be blocked (see https://github.com/jeanpaulrsoucy/covid-19-canada-gov-data/issues/61) so this might also affect GitHub actions. I notified Santé Montreal about this.

**Comment by jeremymoreau** [comment]
Sounds good, seems like we'd have to test whether github actions' servers are being blocked. Another (maybe simpler) possibility is adding a worker processes to the Procfile to have it run on the dokku server (which is hosted on a DigitalOcean VM in Toronto, so maybe less likely to be blocked).

### Procfile format
https://devcenter.heroku.com/articles/procfile
A Procfile declares its process types on individual lines, each with the following format:
`<process type> : <command>`
`<process type>` is an alphanumeric name for your command, such as web, worker, urgentworker, clock, and so on.
`<command>` indicates the command that every dyno of the process type should execute on startup, such as rake jobs:work.
