### ISSUE TITLE
Add automatic processing for QC deaths

### ISSUE THREAD

**Issue by mschoettle** [jeremymoreau/covid19mtl#39]
`data_qc_death_loc.csv` (history of number of deaths by "location") seems to be updated manually currently.

The numbers for Montreal are taken from `data_qc_death_loc_by_region.csv/tableau-rpa-new.csv` and we could do the same for QC (row "Ensemble du Québec").

**Comment by mschoettle** [comment]
Hm, the data in `app/data/data_qc_death_loc.csv` does not seem to match what is in `app/data/sources/<date>/data_qc_death_loc_by_region`. There are also less columns.

Where was the data originally taken from?

**Comment by jeremymoreau** [comment]
I believe those data were from a previous table on the INSPQ website that was unfortunately deleted sometime ago. However, it seems we can get the data from here now: https://www.inspq.qc.ca/sites/default/files/covid/donnees/covid19-hist.csv

Specifically, these columns:
dec_cum_chs_n : CHSLD
dec_cum_rpa_n : RPA
dec_cum_dom_n : Domicile
dec_cum_aut_n: Other

**Comment by mschoettle** [comment]
Ah, good catch. That's much easier :)

**Comment by mschoettle** [comment]
Ah, good catch. That's much easier :)

Do you know what `CH` in relation to death location refers to (saw it in the MTL data)? Hospital?

**Comment by jeremymoreau** [comment]
Yes, CH is Hospital ("Centre Hospitalier").

**Comment by mschoettle** [comment]
If ever we want it to be more detailed split of locations the `data_qc_death_loc.csv` contains more. For now I used `data_qc`. 

I also noticed that the numbers between the two do not match. It's strange. For example, `data_qc` (so `covid19-hist`) for Nov 30th says 3 new deaths, whereas the diff between Nov 29th and Nov 30th for `data_qc_death_loc.csv` is 28.

**Comment by mschoettle** [comment]
> I also noticed that the numbers between the two do not match. It's strange. For example, `data_qc` (so `covid19-hist`) for Nov 30th says 3 new deaths, whereas the diff between Nov 29th and Nov 30th for `data_qc_death_loc.csv` is 28.

It seems to be that the remainder is attributed to prior days. They always report as "28 deaths, 9 of which occurred in the last 24 hours, ...".
