### ISSUE TITLE
New Confirmed cases vs total cases in logspace

### ISSUE THREAD

**Issue by gdevenyi** [jeremymoreau/covid19mtl#6]
This visualisation is really great for showing when things start changing

https://aatishb.com/covidtrends/?region=Canada&location=Alberta&location=British+Columbia&location=Manitoba&location=New+Brunswick&location=Newfoundland+and+Labrador&location=Nova+Scotia&location=Ontario&location=Quebec&location=Saskatchewan

It would be nice to see it for montreal.

**Comment by jeremymoreau** [comment]
I like that graph too, thanks for sharing! Will try adding something like that at some point when I have the time :)

**Comment by shanggejiang** [comment]
figure for Trajectory (Cases vs New Cases)
https://colab.research.google.com/drive/1FRY20DGHOH76S2__pRdMpfgqtxq8Grvc
